stages:
  - renovate
  - build

renovate:
  stage: renovate
  image: renovate/renovate:latest
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_AUTODISCOVER: "false"
    LOG_LEVEL: debug
  script:
    - echo "Token length:$(printenv RENOVATE_TOKEN | wc -c)"
    - renovate $CI_PROJECT_PATH
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

build-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag="$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/_frontend/Dockerfile"
      --destination "cr.hera.lan/stash:${tag}"
      --skip-tls-verify-registry "cr.hera.lan"
      --cache=true
      --cache-run-layers
      --cache-copy-layers
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - changes:
        - .gitlab-ci.yml
        - _frontend/**/*
        - schema.prisma
        - prisma.config.ts

build-worker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag="$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/_worker/Dockerfile"
      --destination "cr.hera.lan/stash-worker:${tag}"
      --skip-tls-verify-registry "cr.hera.lan"
      --cache=true
      --cache-run-layers
      --cache-copy-layers
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - changes:
        - .gitlab-ci.yml
        - _worker/**/*
        - schema.prisma
        - prisma.config.ts

build-gatekeeper:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag="$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/_gatekeeper"
      --dockerfile "${CI_PROJECT_DIR}/_gatekeeper/Dockerfile"
      --destination "cr.hera.lan/stash-gatekeeper:${tag}"
      --skip-tls-verify-registry "cr.hera.lan"
      --cache=true
      --cache-run-layers
      --cache-copy-layers
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - changes:
        - .gitlab-ci.yml
        - _gatekeeper/**/*
        - schema.prisma
